name: census
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - rasterio
  - pyproj
  - geopandas
  - pyogrio
  - pyarrow
  - shapely
  - numpy
  - pandas
  - ipykernel
  - pip
  - pip:
      - geolibre
